CREATE WAREHOUSE IF NOT EXISTS FROSTLINE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS FROSTLINE;

CREATE SCHEMA IF NOT EXISTS FROSTLINE.RAW;