USE DATABASE FROSTLINE;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS BUSINESS (
    data VARIANT
);

CREATE TABLE IF NOT EXISTS REVIEW (
    data VARIANT
);

CREATE TABLE IF NOT EXISTS USER_DATA (
    data VARIANT
);

CREATE TABLE IF NOT EXISTS CHECKIN (
    data VARIANT
);

CREATE TABLE IF NOT EXISTS TIP (
    data VARIANT
);