USE DATABASE FROSTLINE;
USE SCHEMA RAW;

CREATE STREAM IF NOT EXISTS BUSINESS_STREAM ON TABLE BUSINESS;
CREATE STREAM IF NOT EXISTS CHECKIN_STREAM ON TABLE CHECKIN;
CREATE STREAM IF NOT EXISTS REVIEW_STREAM ON TABLE REVIEW;
CREATE STREAM IF NOT EXISTS TIP_STREAM ON TABLE TIP;
CREATE STREAM IF NOT EXISTS USER_DATA_STREAM ON TABLE USER_DATA;